# Generated by Django 5.2 on 2025-04-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='yoga_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.yogaclass'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'yoga_class')},
        ),
    ]
