# Generated by Django 5.2 on 2025-04-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Vinyasa Flow', 'Vinyasa Flow'), ('Hatha Yoga', 'Hatha Yoga')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='minutes')),
                ('capacity', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
