# Generated by Django 5.2 on 2025-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='description',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='title',
            field=models.CharField(choices=[('Vinyasa Flow', 'Vinyasa Flow'), ('Hatha Yoga', 'Hatha Yoga'), ('Yin Yoga', 'Yin Yoga'), ('Power Yoga', 'Power Yoga'), ('Ashtanga', 'Ashtanga'), ('Restorative', 'Restorative'), ('Kundalini', 'Kundalini'), ('Flow & Restore', 'Flow & Restore')], max_length=50),
        ),
    ]
